# Generated by Django 5.0.3 on 2024-03-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session1', '0002_alter_fileupload_options_alter_prostranstvo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Студия',
                'verbose_name_plural': 'Студии',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('session1.studio',),
        ),
        migrations.CreateModel(
            name='TeacherProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('session1.teacher',),
        ),
    ]
