# Generated by Django 5.0.3 on 2024-03-15 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0008_alter_exhibitownerproxy_options'),
        ('teach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], max_length=200)),
            ],
            options={
                'verbose_name': 'День',
                'verbose_name_plural': 'Дни',
            },
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor', models.CharField(max_length=200, verbose_name='ФИО посетителя')),
            ],
            options={
                'verbose_name': 'Посетитель центра',
                'verbose_name_plural': 'Посетители центра',
            },
        ),
        migrations.CreateModel(
            name='ReportCenterState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.studio', verbose_name='Студия')),
            ],
            options={
                'verbose_name': 'Отчет о работе культурного центра',
                'verbose_name_plural': 'Отчеты о работах культурных центров',
            },
        ),
        migrations.CreateModel(
            name='StudioWorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='Дата формирования приказа')),
                ('date_studio_work_start', models.DateField(verbose_name='Дата начала работы студии')),
                ('date_studio_work_end', models.DateField(verbose_name='Дата окончания работы студии')),
                ('time_start', models.TimeField(verbose_name='Время начала работы студии')),
                ('time_end', models.TimeField(verbose_name='Дата окончания работы студии')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.studio', verbose_name='Студия')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.teacher', verbose_name='Преподаватель')),
                ('work_days', models.ManyToManyField(to='teach.day', verbose_name='Рабочие дни')),
            ],
            options={
                'verbose_name': 'Приказ о работе студий',
                'verbose_name_plural': 'Приказы о работах студий',
            },
        ),
        migrations.CreateModel(
            name='TimeTableTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(verbose_name='Дата начала отчета')),
                ('date_end', models.DateField(verbose_name='Дата окончания отчета')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.teacher', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'График работы преподавателя (Отчет)',
                'verbose_name_plural': 'Графики работ преподавателей (Отчеты)',
            },
        ),
        migrations.CreateModel(
            name='ReportToVisitStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(verbose_name='Дата заявки')),
                ('working_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.studioworkreport', verbose_name='Приказ о работе студии')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.visitors', verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Заявка на посещение студии',
                'verbose_name_plural': 'Заявки на посещения студий',
            },
        ),
        migrations.CreateModel(
            name='ReportStudentMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.reportcenterstate', verbose_name='Отчет')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.visitors', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Участники',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
