# Generated by Django 5.0.3 on 2024-03-15 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0008_alter_exhibitownerproxy_options'),
        ('teach', '0002_day_visitors_reportcenterstate_studioworkreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableCellTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(max_length=200, verbose_name='Рабочие дни недели')),
                ('timing', models.CharField(max_length=200, verbose_name='Время занятий')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.studio', verbose_name='Студия')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.timetableteacher', verbose_name='Таблица')),
            ],
            options={
                'verbose_name': 'Строки отчета',
            },
        ),
    ]
