# Generated by Django 5.0.3 on 2024-03-15 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0008_alter_exhibitownerproxy_options'),
        ('teach', '0003_tablecellteacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportcenterstate',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='reportstudentmapping',
            name='visitor',
        ),
        migrations.AddField(
            model_name='reportstudentmapping',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session1.studio', verbose_name='Студия'),
        ),
        migrations.AddField(
            model_name='reportstudentmapping',
            name='visitors',
            field=models.TextField(null=True, verbose_name='Участники'),
        ),
    ]
