# Generated by Django 5.0.3 on 2024-03-15 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0008_alter_exhibitownerproxy_options'),
        ('teach', '0004_remove_reportcenterstate_studio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonimentReportMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aboniments_info', models.TextField(verbose_name='Информация об абониментах')),
                ('total_sum', models.PositiveIntegerField(verbose_name='Итоговая сумма')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.studio', verbose_name='Студия')),
            ],
        ),
        migrations.CreateModel(
            name='AbonimentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sell', models.DateField(verbose_name='Дата продажи абонмента')),
                ('aboniment_type', models.CharField(choices=[('Разовый', 'Разовый'), ('Месячный', 'Месячный'), ('Годовой', 'Годовой')], max_length=200)),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('report_studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.studioworkreport', verbose_name='Приказ о работе студии')),
                ('report_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.reporttovisitstudio', verbose_name='Заявка на посещение студии')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.visitors', verbose_name='Студент')),
            ],
        ),
        migrations.CreateModel(
            name='AbonimentSaleReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.PositiveIntegerField(verbose_name='Итоговая сумма продаж')),
                ('date_started', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('studios', models.ManyToManyField(to='session1.studio', verbose_name='Студии')),
            ],
        ),
        migrations.CreateModel(
            name='CostAbonimentsCreateion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки цен')),
                ('one_type', models.PositiveIntegerField(verbose_name='Единоразовый абонимент')),
                ('month_type', models.PositiveIntegerField(verbose_name='Месячный абонимент')),
                ('year_type', models.PositiveIntegerField(verbose_name='Годовой абонимент')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teach.studioworkreport', verbose_name='Приказ о работе студии')),
            ],
        ),
    ]
