# Generated by Django 5.0.3 on 2024-03-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0005_abonimentreportmapping_abonimentsale_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonimentreportmapping',
            options={'verbose_name': 'Информация о студии по абониментам', 'verbose_name_plural': 'Информации о студиях по абониментам'},
        ),
        migrations.AlterModelOptions(
            name='abonimentsale',
            options={'verbose_name': 'Продажа абониментов', 'verbose_name_plural': 'Продажи абониментов'},
        ),
        migrations.AlterModelOptions(
            name='abonimentsalereport',
            options={'verbose_name': 'Отчет о продажах абонементов', 'verbose_name_plural': 'Отчеты о продажах абониментов'},
        ),
        migrations.AlterModelOptions(
            name='costabonimentscreateion',
            options={'verbose_name': 'Установка цены на абонемент', 'verbose_name_plural': 'Установка цен на абонемент'},
        ),
        migrations.AlterField(
            model_name='abonimentsale',
            name='report_studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teach.studioworkreport', verbose_name='Приказ о работе студии'),
        ),
        migrations.AlterField(
            model_name='abonimentsale',
            name='report_visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teach.reporttovisitstudio', verbose_name='Заявка на посещение студии'),
        ),
        migrations.AlterField(
            model_name='costabonimentscreateion',
            name='month_type',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Месячный абонимент'),
        ),
        migrations.AlterField(
            model_name='costabonimentscreateion',
            name='year_type',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Годовой абонимент'),
        ),
    ]
