# Generated by Django 5.0.3 on 2024-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0006_alter_abonimentreportmapping_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonimentsale',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
