# Generated by Django 5.0.3 on 2024-03-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teach', '0008_abonimentreportmapping_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonimentsalereport',
            name='total_sum',
            field=models.PositiveIntegerField(null=True, verbose_name='Итоговая сумма продаж'),
        ),
    ]
