# Generated by Django 5.0.3 on 2024-03-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session1', '0006_alter_event_spaces_alter_moneyevent_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sell', models.DateTimeField(auto_now_add=True, verbose_name='Дата продажи')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.event', verbose_name='Мероприятие')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер ряда')),
                ('column', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер места')),
                ('cost', models.PositiveIntegerField(verbose_name='Цена')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session1.location', verbose_name='Локация')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session3.sale', verbose_name='Продажа')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.PositiveIntegerField(verbose_name='Номер места')),
                ('row', models.PositiveIntegerField(verbose_name='Номер ряда')),
                ('availability', models.BooleanField(default=True, verbose_name='Доступно?')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.location', verbose_name='Локация')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session3.sale', verbose_name='Продажа')),
            ],
        ),
    ]
