# Generated by Django 5.0.3 on 2024-03-14 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0006_alter_event_spaces_alter_moneyevent_event_and_more'),
        ('session3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveBigIntegerField(verbose_name='Номер ряда')),
                ('available_numbers', models.CharField(max_length=500, verbose_name='Доступные места')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.location', verbose_name='Локация')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session3.sale', verbose_name='Продажа')),
            ],
        ),
    ]
