# Generated by Django 5.0.3 on 2024-03-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session3', '0002_ticketrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cost',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
