# Generated by Django 5.0.3 on 2024-03-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0002_alter_fileupload_options_alter_prostranstvo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='full_name',
            field=models.CharField(max_length=300, unique=True, verbose_name='ФИО'),
        ),
    ]
