# Generated by Django 5.0.3 on 2024-03-14 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0005_rename_location_prostranstvo_loc_location_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='spaces',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session1.prostranstvo', verbose_name='Пространство'),
        ),
        migrations.AlterField(
            model_name='moneyevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.event', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='prostranstvo',
            name='loc',
            field=models.BooleanField(default=False, verbose_name='Есть ли локации?'),
        ),
    ]
