# Generated by Django 5.0.3 on 2024-03-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0006_alter_event_spaces_alter_moneyevent_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('ex_type', models.CharField(choices=[('Внутренняя', 'Внутрення'), ('Внешняя', 'Внешняя')], max_length=200, verbose_name='Тип выставки')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование организации')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='ExhibitOwnerProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session1.studio')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='session1.organization')),
            ],
        ),
        migrations.AlterField(
            model_name='exhibits',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.exhibitownerproxy', verbose_name='Владелец'),
        ),
    ]
