# Generated by Django 5.0.3 on 2024-03-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session1', '0007_exhibition_organization_exhibitownerproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitownerproxy',
            options={'verbose_name': 'Студия или Организация', 'verbose_name_plural': 'Студии или организации'},
        ),
    ]
