# Generated by Django 5.0.3 on 2024-03-13 14:46

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session1', '0002_alter_fileupload_options_alter_prostranstvo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Экспонат',
                'verbose_name_plural': 'Экспонаты',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('session1.exhibits',),
        ),
    ]
