# Generated by Django 5.0.3 on 2024-03-14 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0001_initial'),
        ('session1', '0007_exhibition_organization_exhibitownerproxy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionProxy',
            fields=[
                ('exhibition_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='session1.exhibition')),
            ],
            options={
                'verbose_name': 'Выставка',
                'verbose_name_plural': 'Выставки',
            },
            bases=('session1.exhibition',),
        ),
        migrations.CreateModel(
            name='OrganizationProxy',
            fields=[
                ('organization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='session1.organization')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
            bases=('session1.organization',),
        ),
        migrations.CreateModel(
            name='OrderToCreateExhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(verbose_name='Дата формирования приказа')),
                ('date_start', models.DateTimeField(verbose_name='Дата начала выставки')),
                ('date_end', models.DateTimeField(verbose_name='Дата окончания выставки')),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.exhibition', verbose_name='Выставка')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.prostranstvo', verbose_name='Пространство')),
            ],
            options={
                'verbose_name': 'Приказ о проведении выставки',
                'verbose_name_plural': 'Приказы о проведении выставок',
            },
        ),
        migrations.CreateModel(
            name='OrderExhibitionToExhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_to_provide', models.DateTimeField(verbose_name='Дата передачи')),
                ('order_to_create_exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.ordertocreateexhibition', verbose_name='Приказ о проведении выставки')),
            ],
            options={
                'verbose_name': 'Акт передачи экспонатов на выставку',
                'verbose_name_plural': 'Акты передачи экспонатов на выставку',
            },
        ),
        migrations.CreateModel(
            name='OrderExhibitionFromAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_getting', models.DateTimeField(verbose_name='Дата получения экспонатов')),
                ('creation_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.ordertocreateexhibition', verbose_name='Приказ о проведении выставки')),
            ],
            options={
                'verbose_name': 'Приказ о поступлении экспонатов от сторонней стороны',
                'verbose_name_plural': 'Приказы о поступлении экспонатов от сторонней стороны',
            },
        ),
        migrations.CreateModel(
            name='OrderToReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_return', models.DateTimeField(verbose_name='Дата возврата экспонатов')),
                ('order_to_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.ordertocreateexhibition', verbose_name='Приказ о проведении выставки')),
            ],
            options={
                'verbose_name': 'Акт возврата экспонатов',
            },
        ),
        migrations.CreateModel(
            name='ExhibitAuthorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=300, verbose_name='Владелец')),
                ('exhibit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session1.exhibits', verbose_name='Экспонат')),
                ('order_to_get', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culture.orderexhibitionfromauthors', verbose_name='Приказ о получении')),
                ('order_to_provide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culture.orderexhibitiontoexhibit', verbose_name='Акт передачи экспонатов на выставку')),
                ('order_to_create', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture.ordertocreateexhibition', verbose_name='Приказ о проведении выставки')),
                ('order_to_return', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='culture.ordertoreturn', verbose_name='Акт возврата экспоната')),
            ],
        ),
    ]
