# Generated by Django 5.0.3 on 2024-03-14 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0002_exhibitionproxy_organizationproxy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordertoreturn',
            options={'verbose_name': 'Акт возврата экспонатов', 'verbose_name_plural': 'Акты возврата экспонатов'},
        ),
    ]
