# Generated by Django 5.0.3 on 2024-03-15 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture', '0003_alter_ordertoreturn_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exhibitauthormapping',
            options={'verbose_name': 'Маршрут', 'verbose_name_plural': 'Маршруты'},
        ),
    ]
