name: Django CI with Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage codecov

    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          nc -z localhost 5432 && echo "PostgreSQL is up" && exit 0
          echo "Waiting for PostgreSQL..."
          sleep 5
        done
        exit 1

    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      run: |
        python manage.py migrate

    - name: Run tests with coverage
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
      run: |
        coverage run --source='nto' manage.py test

    - name: Generate Coverage Report
      run: |
        coverage xml
        coverage report

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true